import './index.less'
// import './0_basicTemplate'
// import './1_transformObject'
// import './2_animations'
// import './03_cameras'
// import './04_fullScreen'
// import './05_geometry'
// import './06_debugUi'
// import './07_textTures'
// import './08_material'
// import './09_3Dtext'
// import './10_light'
// import './11_shadow'
import './12_ghost_home'
